In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.4.1


In [3]:
import numpy as np
import time 

In [4]:
size = 10000000
start = time.time()
l = [i**2 for i in range (size)]
end = time.time()
print(f"python list time : {end-start}")

python list time : 2.4434351921081543


In [5]:
size = 1000000
start = time.time()
arr = np.arange(size)**2
end = time.time()
print(f"Numpy Arre time:{end - start}")

Numpy Arre time:0.017925024032592773


In [6]:
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
print(len(a))

5


In [9]:
print(a.size)

5


In [10]:
print(a.dtype)

int64


In [11]:
a = np.array([10,20,"30",40,50])
print(a)

['10' '20' '30' '40' '50']


In [12]:
print(a.dtype)

<U21


In [13]:
a = np.array([10,20,"30",40.5,50])
print(a)

['10' '20' '30' '40.5' '50']


In [14]:
print(a.dtype)

<U32


In [15]:
a = np.array(["hallo","world","python#","&and"])
print(a)
print(a.dtype)

['hallo' 'world' 'python#' '&and']
<U7


In [16]:
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [17]:
print(a[0])

10


In [18]:
print(a[4])

50


In [19]:
print(a[1:3])

[20 30]


In [20]:
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [21]:
print(a[a>20])

[30 40 50]


In [22]:
data = np.array([8,7,-1,9,-2,-7,0,-9,12])
Possitive = data[data>0]
Negative = data[data<0]
print(Possitive)
print(Negative)

[ 8  7  9 12]
[-1 -2 -7 -9]


In [23]:
a = np.array([78,42,19,13,24,11,7])
Odd = a[a%2!=0]
Even = a[a%2==0]
print(Odd)
print(Even)

[19 13 11  7]
[78 42 24]


In [24]:
a = np.array([10,20,30,40,50])
print(a+5)

[15 25 35 45 55]


In [25]:
print(a-5)

[ 5 15 25 35 45]


In [26]:
print(a*5)

[ 50 100 150 200 250]


In [27]:
print(a**2)

[ 100  400  900 1600 2500]


In [28]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)
print(type(a),len(a),id(a))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'> 3 2578420525424


In [29]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [30]:
print(a[0,0])

10


In [31]:
print(a[1,2])

60


In [32]:
a = np.array([10,20,30,40,50,60,70,80,90,100])
print(a.shape)

(10,)


In [33]:
a = np.array([[10,20,30,40,50,60,70,80,90,100]])
print(a.shape)

(1, 10)


In [34]:
a = np.array([[10,20],[30,40],[50,60],[70,80],[90,100]])
print(a.shape)

(5, 2)


# second day of class :-

In [37]:
import numpy as np

In [38]:
a = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120],[130,140,150,160]])
print(a)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


In [39]:
print(a.shape)

(4, 4)


In [40]:
print(a[0][1:3])

[20 30]


In [43]:
print(a[0,1:3])

[20 30]


In [44]:
print(a)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


In [47]:
a = np.array([[55,81,36,78],[51,42,36,95],[71,85,12,66],[99,74,15,20]])
print(a)

[[55 81 36 78]
 [51 42 36 95]
 [71 85 12 66]
 [99 74 15 20]]


In [49]:
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.min(a))
print(np.max(a))

916
57.25
60.5
12
99


In [48]:
print(a[1,0:2])

[51 42]


In [50]:
print(a[: , 0])

[55 51 71 99]


In [51]:
#[70,80]and[30,70,110]
print(a[1,2:])

[36 95]


In [52]:
print(a[a>100])

[]


In [80]:
b = np.array,([[55,81,36,78],[51,42,36,95],[71,85,12,66],[99,74,15,20]])
print(b)

(<built-in function array>, [[55, 81, 36, 78], [51, 42, 36, 95], [71, 85, 12, 66], [99, 74, 15, 20]])


In [81]:
print(a*b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [57]:
print(a/b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [95]:
a = np.array([[5,14,3,8,19,11,1]])
print(a)

[[ 5 14  3  8 19 11  1]]


In [59]:
a[1] = 100
print(a)

[  5 100   3   8  19  11   1]


In [ ]:
a[]

In [22]:
a = np.array([5,14,3,8,19,11,1])
print(a)

[ 5 14  3  8 19 11  1]


In [23]:
a[a>10] = -1

In [24]:
print(a)

[ 5 -1  3  8 -1 -1  1]


In [25]:
a = np.array([5,14,3,8,19,12,15])
print(a)

[ 5 14  3  8 19 12 15]


In [28]:
a[a%3==0] = 0

In [29]:
print(a)

[ 5 14  0  8  0  0  0]


In [30]:
a = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120],[130,140,150,160]])
print(a)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


In [31]:
a[0,0 ] = 100

In [34]:
print(a)

[[100  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


In [36]:
# arthmetik function 
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [37]:
print(np.sum(a))

150


In [38]:
print(np.mean(a))

30.0


In [39]:
print(np.median(a))

30.0


In [42]:
print(np.min(a))
print(np.max(a))

10
50


In [43]:
a = np.array([5,9,3,1,4,6])
print(a)

[5 9 3 1 4 6]


In [45]:
print(np.argmin(a))

3


In [47]:
print(np.argmax(a))

1


In [77]:
a = np.array([[55,81,36]])

In [78]:
print(np.argmin(a))

2


In [79]:
print(np.argmin(a))

2


In [71]:
y25 = np.array([[14,15,36],[31,24,19,],[39,67,40],[48,29,51]])
print(y25)

[[14 15 36]
 [31 24 19]
 [39 67 40]
 [48 29 51]]


In [72]:
print(f"total sales : {np.sum(y25)}")
print(f"Q1 sales :{np.mean(y25)}")
print(f"Q2 sales :{np.median(y25)}")
print(f"Q3 sales :{np.min(y25)}")
print(f"Q4 sales :{np.max(y25)}")

total sales : 413
Q1 sales :34.416666666666664
Q2 sales :33.5
Q3 sales :14
Q4 sales :67


In [84]:
# Zero method:-
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [85]:
total = np.zeros((4,3))
print(total)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [86]:
total+=y25
print(total)

[[14. 15. 36.]
 [31. 24. 19.]
 [39. 67. 40.]
 [48. 29. 51.]]


In [2]:
import numpy as np
total = np.zeros((2,3))
print(total)

[[0. 0. 0.]
 [0. 0. 0.]]


# claas 2 and 

In [3]:
# Arange Method ---- np.arange(start , stop , step)
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
a = np.arange(15,35,2)

In [5]:
print(a)

[15 17 19 21 23 25 27 29 31 33]


In [9]:
# Reshape Method ---- Var.reshape(size)
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [11]:
print(a.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
a = np.arange(1,7).reshape(6,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [13]:
# Transpose Method ---- np.transpose(var)
a = np.arange(20,26).reshape(3,2)
print(a)
print(a.shape)

[[20 21]
 [22 23]
 [24 25]]
(3, 2)


In [15]:
a = np.transpose(a)
print(a)
print(a.shape)

[[20 21]
 [22 23]
 [24 25]]
(3, 2)


In [16]:
a = np.random.rand(10)*100
print(a)

[94.36687346 92.88395127 74.19379106 73.23901751 86.17615946 56.54516709
 38.5744615  17.17316242 35.7248085  97.16731288]


In [17]:
a = np.random.rand(5,4)*10
print(a)

[[9.25266303 5.40328914 3.45668876 1.21936124]
 [5.23408759 9.56951011 3.75995456 4.8004705 ]
 [1.03643499 1.04277029 6.87710335 2.88827627]
 [4.2945756  0.96246784 5.88680052 3.02791269]
 [7.87464584 2.88793548 9.91083217 0.67532169]]


In [20]:
# np.random.randint(min,max,size)
a = np.random.randint(55,90,30)
print(a)

[57 57 59 76 61 87 72 65 62 61 89 78 75 85 70 60 88 65 78 62 78 57 77 79
 89 71 88 88 72 66]


In [22]:
a = np.random.randint(108,182,(3,3))
print(a)

[[152 135 124]
 [152 136 125]
 [150 163 139]]


In [ ]:
import random
count = 0
while True:
    num = int(input("Enter Number:"))
    r = random.randint(1,9)
    count+=1
    if num == r:
        print(f" you Gurssed it right in {count} Attempt!")
        break
    else:
        print("Again!")

Enter Number: 8


Again!


Enter Number: 7


Again!


Enter Number: 6


Again!


Enter Number: 5


Again!


Enter Number: 4


Again!


Enter Number: 6


Again!


Enter Number: 7


Again!


Enter Number: 8


Again!


Enter Number: 3


Again!
